% Generated by "erim_known.es" on 2014-8-20, 15:26:25 UTC
% File: erim_known_attrs.hrl
% 
-define(XML_KNOWN_ATTRS,
        [arcrole,scheme,uri,affiliation,ref,category,ver,hash,max_items,node,
         mechanism,type,show,system,base,targetNamespace,schemaLocation,
         default,status,mdate,ask,action,elementFormDefault,finalDefault,
         'block-size',version,minOccurs,cdate,from,itemType,source,fixed,
         attributeFormDefault,title,label,publisher,feature,code,stamp,ext,
         jid,public,href,immutable,stanza,order,name,xpath,abstract,refer,
         nillable,by,sid,subscription,id,processContents,namespace,mixed,
         maxOccurs,subid,substitutionGroup,final,notify,actuate,role,
         memberTypes,block,use,seq,var,value,location,expiry,to,form,
         blockDefault,term,'$end_of_table']).

