% Generated by "erim_known.es" on 2014-8-20, 15:26:25 UTC
% File: erim_known_attrs.erl
% 
-module(erim_known_attrs).
-export([attr_as_list/1]).

attr_as_list('arcrole') -> "arcrole";
attr_as_list('scheme') -> "scheme";
attr_as_list('uri') -> "uri";
attr_as_list('affiliation') -> "affiliation";
attr_as_list('ref') -> "ref";
attr_as_list('category') -> "category";
attr_as_list('ver') -> "ver";
attr_as_list('hash') -> "hash";
attr_as_list('max_items') -> "max_items";
attr_as_list('node') -> "node";
attr_as_list('mechanism') -> "mechanism";
attr_as_list('type') -> "type";
attr_as_list('show') -> "show";
attr_as_list('system') -> "system";
attr_as_list('base') -> "base";
attr_as_list('targetNamespace') -> "targetNamespace";
attr_as_list('schemaLocation') -> "schemaLocation";
attr_as_list('default') -> "default";
attr_as_list('status') -> "status";
attr_as_list('mdate') -> "mdate";
attr_as_list('ask') -> "ask";
attr_as_list('action') -> "action";
attr_as_list('elementFormDefault') -> "elementFormDefault";
attr_as_list('finalDefault') -> "finalDefault";
attr_as_list('block-size') -> "block-size";
attr_as_list('version') -> "version";
attr_as_list('minOccurs') -> "minOccurs";
attr_as_list('cdate') -> "cdate";
attr_as_list('from') -> "from";
attr_as_list('itemType') -> "itemType";
attr_as_list('source') -> "source";
attr_as_list('fixed') -> "fixed";
attr_as_list('attributeFormDefault') -> "attributeFormDefault";
attr_as_list('title') -> "title";
attr_as_list('label') -> "label";
attr_as_list('publisher') -> "publisher";
attr_as_list('feature') -> "feature";
attr_as_list('code') -> "code";
attr_as_list('stamp') -> "stamp";
attr_as_list('ext') -> "ext";
attr_as_list('jid') -> "jid";
attr_as_list('public') -> "public";
attr_as_list('href') -> "href";
attr_as_list('immutable') -> "immutable";
attr_as_list('stanza') -> "stanza";
attr_as_list('order') -> "order";
attr_as_list('name') -> "name";
attr_as_list('xpath') -> "xpath";
attr_as_list('abstract') -> "abstract";
attr_as_list('refer') -> "refer";
attr_as_list('nillable') -> "nillable";
attr_as_list('by') -> "by";
attr_as_list('sid') -> "sid";
attr_as_list('subscription') -> "subscription";
attr_as_list('id') -> "id";
attr_as_list('processContents') -> "processContents";
attr_as_list('namespace') -> "namespace";
attr_as_list('mixed') -> "mixed";
attr_as_list('maxOccurs') -> "maxOccurs";
attr_as_list('subid') -> "subid";
attr_as_list('substitutionGroup') -> "substitutionGroup";
attr_as_list('final') -> "final";
attr_as_list('notify') -> "notify";
attr_as_list('actuate') -> "actuate";
attr_as_list('role') -> "role";
attr_as_list('memberTypes') -> "memberTypes";
attr_as_list('block') -> "block";
attr_as_list('use') -> "use";
attr_as_list('seq') -> "seq";
attr_as_list('var') -> "var";
attr_as_list('value') -> "value";
attr_as_list('location') -> "location";
attr_as_list('expiry') -> "expiry";
attr_as_list('to') -> "to";
attr_as_list('form') -> "form";
attr_as_list('blockDefault') -> "blockDefault";
attr_as_list('term') -> "term";
attr_as_list(undefined) -> "";
attr_as_list(A) when is_atom(A) -> atom_to_list(A);
attr_as_list(S) when is_list(S) -> S.

