% Generated by "erim_known.es" on 2014-8-20, 15:26:24 UTC
% File: erim_known_nss.erl
% 
-module(erim_known_nss).
-export([ns_as_list/1]).

ns_as_list('http://www.w3.org/1999/xlink') -> "http://www.w3.org/1999/xlink";
ns_as_list('urn:xmpp:ping') -> "urn:xmpp:ping";
ns_as_list('http://jabber.org/protocol/chatstates') -> "http://jabber.org/protocol/chatstates";
ns_as_list('http://jabber.org/protocol/ibb') -> "http://jabber.org/protocol/ibb";
ns_as_list('storage:rosternotes') -> "storage:rosternotes";
ns_as_list('urn:ietf:params:xml:ns:xmpp-session') -> "urn:ietf:params:xml:ns:xmpp-session";
ns_as_list('jabber:client') -> "jabber:client";
ns_as_list('urn:ietf:params:xml:ns:xmpp-sasl') -> "urn:ietf:params:xml:ns:xmpp-sasl";
ns_as_list('urn:xmpp:delay') -> "urn:xmpp:delay";
ns_as_list('vcard-temp:x:update') -> "vcard-temp:x:update";
ns_as_list('http://jabber.org/protocol/compress') -> "http://jabber.org/protocol/compress";
ns_as_list('http://jabber.org/protocol/pubsub#event') -> "http://jabber.org/protocol/pubsub#event";
ns_as_list('jabber:iq:private') -> "jabber:iq:private";
ns_as_list('http://jabber.org/protocol/caps') -> "http://jabber.org/protocol/caps";
ns_as_list('urn:ietf:params:xml:ns:xmpp-bind') -> "urn:ietf:params:xml:ns:xmpp-bind";
ns_as_list('jabber:component:connect') -> "jabber:component:connect";
ns_as_list('http://jabber.org/features/iq-register') -> "http://jabber.org/features/iq-register";
ns_as_list('jabber:x:data') -> "jabber:x:data";
ns_as_list('urn:xmpp:time') -> "urn:xmpp:time";
ns_as_list('jabber:component:accept') -> "jabber:component:accept";
ns_as_list('jabber:iq:rpc') -> "jabber:iq:rpc";
ns_as_list('vcard-temp') -> "vcard-temp";
ns_as_list('jabber:iq:privacy') -> "jabber:iq:privacy";
ns_as_list('http://www.w3.org/2001/XMLSchema') -> "http://www.w3.org/2001/XMLSchema";
ns_as_list('roster:delimiter') -> "roster:delimiter";
ns_as_list('http://etherx.jabber.org/streams') -> "http://etherx.jabber.org/streams";
ns_as_list('http://jabber.org/protocol/pubsub#errors') -> "http://jabber.org/protocol/pubsub#errors";
ns_as_list('urn:ietf:params:xml:ns:xmpp-tls') -> "urn:ietf:params:xml:ns:xmpp-tls";
ns_as_list('http://schemas.ogf.org/occi') -> "http://schemas.ogf.org/occi";
ns_as_list('jabber:server') -> "jabber:server";
ns_as_list('urn:ietf:params:xml:ns:xmpp-stanzas') -> "urn:ietf:params:xml:ns:xmpp-stanzas";
ns_as_list('jabber:server:dialback') -> "jabber:server:dialback";
ns_as_list('jabber:iq:gateway') -> "jabber:iq:gateway";
ns_as_list('http://jabber.org/protocol/disco#items') -> "http://jabber.org/protocol/disco#items";
ns_as_list('jabber:iq:last') -> "jabber:iq:last";
ns_as_list('jabber:iq:roster') -> "jabber:iq:roster";
ns_as_list('urn:ietf:params:xml:ns:xmpp-streams') -> "urn:ietf:params:xml:ns:xmpp-streams";
ns_as_list('jabber:x:roster') -> "jabber:x:roster";
ns_as_list('http://jabber.org/protocol/pubsub#owner') -> "http://jabber.org/protocol/pubsub#owner";
ns_as_list('http://jabber.org/protocol/waitinglist') -> "http://jabber.org/protocol/waitinglist";
ns_as_list('jabber:iq:register') -> "jabber:iq:register";
ns_as_list('http://jabber.org/features/compress') -> "http://jabber.org/features/compress";
ns_as_list('jabber:iq:search') -> "jabber:iq:search";
ns_as_list('http://jabber.org/protocol/disco#info') -> "http://jabber.org/protocol/disco#info";
ns_as_list('http://jabber.org/protocol/pubsub') -> "http://jabber.org/protocol/pubsub";
ns_as_list('urn:ietf:params:xml:ns:xmpp-e2e') -> "urn:ietf:params:xml:ns:xmpp-e2e";
ns_as_list(undefined) -> "";
ns_as_list(A) when is_atom(A) -> atom_to_list(A);
ns_as_list(S) when is_list(S) -> S.

